[package]
name = "TestDep"
type = "bin"
authors = [""]

[dependencies]
local_dependency = { path = "./testing/LocalDep" }
local_dependency_v1 = { path = "./testing/LocalDepV1" }
local_dependency_v2 = { path = "./testing/LocalDepV2" }
local_dependency_with_lampe = { path = "./testing/LocalDepWithLampe" }
local_dependency_with_lampe_v1 = { path = "./testing/LocalDepWithLampeV1" }
local_dependency_with_lampe_v2 = { path = "./testing/LocalDepWithLampeV2" }
git_dependency = { tag = "main", git = "https://github.com/reilabs/lampe", directory = "testing/TestDep/testing/GitDep" }
git_dependency_v1 = { tag = "main", git = "https://github.com/reilabs/lampe", directory = "testing/TestDep/testing/GitDepV1" }
git_dependency_v2 = { tag = "main", git = "https://github.com/reilabs/lampe", directory = "testing/TestDep/testing/GitDepV2" }
git_dependency_with_lampe = { tag = "main", git = "https://github.com/reilabs/lampe", directory = "testing/TestDep/testing/GitDepWithLampe" }
git_dependency_with_lampe_v1 = { tag = "main", git = "https://github.com/reilabs/lampe", directory = "testing/TestDep/testing/GitDepWithLampeV1" }
git_dependency_with_lampe_v2 = { tag = "main", git = "https://github.com/reilabs/lampe", directory = "testing/TestDep/testing/GitDepWithLampeV2" }

